version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: bundle install
      - run:
          name: Rubocop
          command: rubocop -D
      - run:
          name: Running tests
          command: bundle exec rspec
